config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  authenticate :user do
    mount Resque::Server => "/resque"
  end

  # Mount letter_opener web interface
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Test email route
  get 'test_email', to: 'test_emails#send_test'

  namespace :admin do
    resources :users
  end

  resources :kommunities, only: [:new, :create, :edit, :update], param: :kommunity

  scope ':kommunity' do

    get '/',
        to: 'kommunities#show',
        as: :kommunity_show

    resources :events, only: [:index, :new, :create, :edit, :update, :show] do
      member do

        post 'assign-data-form',
             to: 'event_data_form_entity_groups#assign_data_form_entity',
             as: :assign_data_form

        post 'create-form-set',
             to: 'event_data_form_entity_groups#create',
             as: :create_form_set

        delete 'destroy-form-set',
               to: 'event_data_form_entity_groups#destroy',
               as: :destroy_form_set


        get 'update-registration-status-counter',
            to: 'event_data_form_entity_groups#update_registration_status_counter',
            as: :update_registration_status_counter


        delete 'remove-data-form-entity',
               to: 'data_form_entities_events#remove_data_form_entity',
               as: :remove_data_form_entity

        post 'form/update-visibility',
            to: 'data_form_entities_events#update_visibility',
            as: :update_form_visibility


        put 'update-event-status',
            to: 'events#update_event_status',
            as: :update_event_status

        put 'update-header-image',
            to: 'events#update_header_image',
            as: :update_header_image


        get 'all-responses',
            to: 'events#all_responses',
            as: :all_responses


        get 'resources',
            to: 'events#public_resources',
            as: :public_resources


        get 'session-discussions',
            to: 'speaker_resources#session_discussions',
            as: :session_discussion


        resources :event_location_tracks, path: 'event-location-tracks', only: [:create, :destroy], shallow: true do
          resources :track_slots, path: 'track-slots', only: [:create, :destroy], shallow: true
        end


        resources :comments, only: [:create, :destroy], shallow: true do
          resources :comments, only: [:create, :destroy]
        end


        resources :speaker_resources, path: 'speaker-resources', only: [:new, :create, :update]


      end

      resources :locations, only: [:create, :destroy]

      resources :event_updates, only: [:create, :destroy]

    end

    resources :data_forms, path: 'data-forms', only: [:new, :create, :edit, :update]


    resources :event_entry_passes, path: 'event-entry-passes', only: [:create] do
      member do
        patch :toggle_attendance, as: 'toggle-attendance'
        patch :toggle_uninvited, as: 'toggle-uninvited'
      end

      collection do
        get :auto_attendance, as: 'auto-attendance'
        patch :mark_attendance, as: 'mark-attendance'
      end
    end




    # INDIVIDUAL URLS

    # data_form_entity_responses_controller
    get 'fill-form',
        to: 'data_form_entity_responses#fill_form',
        as: :fill_form_response


    post 'response',
         to: 'data_form_entity_responses#submit_form',
         as: :submit_form_response

    put 'form-responses/update-registration_status',
        to: 'data_form_entity_response_groups#update_registration_status',
        as: :update_response_registration_status



    get 'update-rsvp',
        to: 'data_form_entity_response_groups#update_rsvp',
        as: :update_rsvp



    # data_form_entities_controller
    get 'form-responses',
        to: 'data_form_entities#form_responses',
        as: :form_responses

    get 'form-responses-data',
        to: 'data_form_entities#form_responses_data',
        as: :form_responses_data


    # data_form_entity_responses_controller
    put 'user-event-locations/update-selected-location',
        to: 'user_event_locations#update_selected_location',
        as: :update_user_event_selected_location



    #event_communications_mailer
    resources :event_communication_mailers, path: "event-communication-mailers" do
      collection do
        get :data_form_entity_response_group_rsvp_email, path: "user-rsvp-email"
        post :send_data_form_entity_response_group_rsvp_email, path: "send-user-rsvp-email"
        get :event_data_form_entity_group_rsvp_email, path: "event-users-rsvp-email"
        post :send_event_data_form_entity_group_rsvp_email, path: "send-event-users-rsvp-email"
        get :data_form_entity_response_group_entry_pass_email, path: "user-entry-pass-email"
        post :send_data_form_entity_response_group_entry_pass_email, path: "send-user-entry-pass-email"
        get :event_data_form_entity_group_entry_pass_email, path: "event-users-entry-pass-email"
        post :send_event_data_form_entity_group_entry_pass_email, path: "send-event-users-entry-pass-email"

        get :feedback_email, path: "feedback-email"
        post :send_feedback_email, path: "send-feedback-email"

        get :registration_email, path: "registration-email"
        post :send_registration_email, path: "send-registration-email"
      end
    end

    resources :discussions, only: [:create]

  end


  resources :user_messages, only: [:create]



  match '*all', to: proc { [204, {}, ['']] }, via: :options

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  root "home#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_form_entity.rb
class DataFormEntity < ApplicationRecord
  # this model makes the form generic, the same form can be assigned to an event or any other thing as well
  # extend FriendlyId
  # friendly_id :name, use: :slugged
  belongs_to :data_form
  belongs_to :entity, polymorphic: true
  has_many :questions, through: :data_form
  has_many :data_form_entity_responses

  enum visibility: [:yet_to_announce, :open_but_invisible, :open, :members_who_have_attended, :closed, :on_the_spot_uninvited]

  def can_fill_event_form(user)
    if (self.open? || self.open_but_invisible? || self.on_the_spot_uninvited?) || (!user.blank? && ((user.role?(:system_administrator, nil) || user.role?(:organizer, self.entity.event.kommunity_id)) || (self.members_who_have_attended? && self.entity.event.event_entry_passes.where(user: user).length > 0)))
      return true
    end
    return false
  end

end

app/controllers/data_form_entities_controller.rb
class DataFormEntitiesController < ApplicationController
  # before_action :set_kommunity
  before_action :authenticate_user!
  before_action :set_event_data_form_entity_group, only: [:form_responses, :form_responses_data]
  before_action :set_page_numbers, only: [:form_responses, :form_responses_data]
  before_action :access_allowed?



  # get the list of all entries filled for an event
  def form_responses
    @registration_types = RegistrationType.all
    @selected_status = params[:registration_status]
    @entry_passes = @edfeg.event.event_entry_passes.select(:id)
  end




  def form_responses_data

    if !params[:registration_status].blank? && params[:registration_status] != 'all'

      @responses = @edfeg.data_form_entity_response_groups.where('registration_status_id = ?', params[:registration_status].to_i).order(:created_at).offset(@count * (@page - 1)).limit(@count)

    else
      @responses = @edfeg.data_form_entity_response_groups.order(:created_at).offset(@count * (@page - 1)).limit(@count)

    end
    @selected_status = params[:registration_status]


    @registration_types = RegistrationType.all
    @entry_passes = @edfeg.event.event_entry_passes.where(user_id: @responses.map(&:user_id))


    @pending_data = @responses.length == @count ? true : false



  end




  private

  def set_event_data_form_entity_group
    @edfeg = EventDataFormEntityGroup.includes(data_form_entities: {data_form: {questions: [:question_choices, :data_form_entity_response_values]}}).find(params[:event_data_form_entity_group_id].to_i)
    RolePermission.event = @edfeg.event

  end

  def set_page_numbers
    @page = params[:page].blank? ? 1 : params[:page].to_i
    @count = params[:count].blank? ? 20 : params[:count].to_i
  end

end

app/views/data_form_entities/_form_response_row.html.erb
<tr>
  <td class="pt-2 pb-0">
    <p>
      <%= index %>
    </p>
  </td>
  <th scope="row" class="pt-2 pb-2 sticky-box">
    <p class="mb-0">
      <%= dferg.user.name %>
    </p>
    <div class="user-avatar">
      <%= image_tag url_for(dferg.user.avatar), width: 50 %>
    </div>
    <p>
      <%= dferg.user.email %>
    </p>
    <% if(!@edfeg.registration_type.blank?) %>
      <%= render 'data_form_entity_response_groups/registration_status_actions', dferg: dferg, entry_pass: @entry_passes.select{|ep| ep.user == dferg.user && ep.event == @edfeg.event}.first %>
    <% end %>
  </th>
  <td scope="row" class="pt-2 pb-0">
    <p class="text-muted designation"><%= dferg.user.designation %></p>
    <div class="speaker-social-links d-flex justify-content-center">
      <% if dferg.user.personal_website %>
        <a target="_blank" href="<%= complete_url(dferg.user.personal_website) %>" class="p-2 text-dark">
          <i class="fas fa-info"></i>
        </a>
      <% end %>
      <% if dferg.user.twitter %>
        <a target="_blank" href="<%= twitter_url(dferg.user.twitter) %>" class="p-2 text-dark">
          <i class="fab fa-twitter"></i>
        </a>
      <% end %>
      <% if dferg.user.github %>
        <a target="_blank" href="<%= complete_url(dferg.user.github) %>" class="p-2 text-dark">
          <i class="fab fa-github"></i>
        </a>
      <% end %>
      <% if dferg.user.linkedin %>
        <a target="_blank" href="<%= complete_url(dferg.user.linkedin) %>" class="p-2 text-dark">
          <i class="fab fa-linkedin-in"></i>
        </a>
      <% end %>
    </div>
  </td>
  <% if @edfeg.registration_type?([NameValues::RegistrationsType::SPEAKER]) %>
    <td>
      <% if dferg.speaker_resource %>
        <div>
          <%= wrap_url_anchor(simple_format(dferg.speaker_resource.session_details_links)) %>
        </div>
      <% end %>
    </td>
  <% end %>
  <% @edfeg.data_form_entities.each do |dfe| %>
    <% dfe.data_form.questions.with_deleted.each do |question| %>
      <% dferg.data_form_entity_responses.each do |dfer| %>
        <td class="pt-2 pb-0">
          <p>
            <%= wrap_url_anchor(DataFormEntityResponseValue.get_response_text(question, dfer)) %>
          </p>
        </td>
      <% end %>
    <% end %>
  <% end %>
  <td class="pt-2 pb-0">
  </td>
</tr>

app/views/data_form_entities/_form_type_select.html.erb
<div>

  <p>
    Select Registration Type

  </p>
  <% @registration_types.each do |reg| %>

    <%= link_to reg.name, change_responses_registration_type_path(event_id: event, data_form_entity_id: dfe, registration_type: reg.id), method: :put, class: "#{'active-registration-type' if(reg == dfe.registration_type)}" %>

  <% end %>

</div>

app/views/data_form_entities/_group_email_controls.html.erb
<div id="registration-communication-group-actions-<%= edfeg.id %>">
  <ul class="list-group d-flex flex-row">

    <% if @edfeg.registration_type?([NameValues::RegistrationsType::ATTENDEE, NameValues::RegistrationsType::SPEAKER]) %>
    <li class="list-group-item">
      <%= link_to "Send Remaining RSVP Emails", event_data_form_entity_group_rsvp_email_event_communication_mailers_path(event_data_form_entity_group: edfeg.id), remote: true %>
    </li>
    <li class="list-group-item">
      <%= link_to "Resend All RSVP Emails", event_data_form_entity_group_rsvp_email_event_communication_mailers_path(event_data_form_entity_group: edfeg.id, force: true), remote: true %>
    </li>
    <li class="list-group-item">
      <%= link_to "Send Remaining Entry Passes", event_data_form_entity_group_entry_pass_email_event_communication_mailers_path(event_data_form_entity_group: edfeg.id), remote: true %>
    </li>
    <li class="list-group-item">
      <%= link_to "Resend All Entry Passes", event_data_form_entity_group_entry_pass_email_event_communication_mailers_path(event_data_form_entity_group: edfeg.id, force: true), remote: true %>
    </li>
    <% end %>
  </ul>

</div>

app/views/data_form_entities/form_responses.html.erb
<% content_for :page_title do %>
  <%= @kommunity.name %> | <%= @edfeg.event.name %> | <%= @edfeg.name %> Responses
<% end %>
<section class="container-fluid" id="data-form-entities-form-responses">
  <div>
    <div class="card">
      <div class="card-header">
        <%= @edfeg.event.name %> :: Responses :: <strong><%= @edfeg.name %></strong>
      </div>
      <div class="card-body">
        <div class="response-group-email-controls">
          <%= render 'group_email_controls', edfeg: @edfeg %>
        </div>
        <div class="mt-3">
          <ul class="list-group d-flex flex-row">
            <% @edfeg.data_form_entities.order('created_at').each do |dfe| %>
              <li class="list-group-item">
                <%= link_to 'On The Spot Registration', fill_form_response_path(data_form_entity_id: dfe, for_other_user: true, ots: true), class: 'ml-2 text-primary' %>
              </li>
              <li class="list-group-item">
                <%= link_to 'Attendance Page', auto_attendance_event_entry_passes_path(event: @edfeg.event), class: 'ml-2 text-primary' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-hover table-fixed">
        <thead>
          <tr>
            <th scope="col" class="sticky-row sticky-col">
              <p>#</p>
            </th>
            <th scope="col" class="sticky-row sticky-box">
              <p>Name / Email</p>
              <p>
                Registration Status / Actions
                <br>
                <small>Locations displayed in the order of preference (if) selected by user</small>
              </p>
              <div>
                <%= render 'event_data_form_entity_groups/registration_status_counter_filter', edfeg: @edfeg, selected_status: @selected_status %>
              </div>
            </th>
            <th scope="col" class="sticky-row">
              <p>Detalles del perfil</p>
            </th>
            <% if @edfeg.registration_type?([NameValues::RegistrationsType::SPEAKER]) %>
              <th class="sticky-row">
                <p>Session Flow + Slides (Links)</p>
              </th>
            <% end %>
            <% @edfeg.data_form_entities.each do |dfe| %>
              <%  dfe.data_form.questions.with_deleted.each do |question| %>
                <th scope="col" class="sticky-row">
                  <p>
                    <%= question.title %>
                  </p>
                </th>
              <% end %>
            <% end %>
          </tr>
        </thead>
        <tbody id="form-responses-container">
          <!--TODO Optimize the query to show responses-->
        </tbody>
      </table>
    </div>
  </div>
  <script>
    function getFormResponses(registrationStatus, kommunity, eventDataFormEntityGroupId, page){
        $.getScript( `/${kommunity}/form-responses-data?event_data_form_entity_group_id=${eventDataFormEntityGroupId}&page=${page}&registration_status=${registrationStatus}` )
            .done(function( script, textStatus ) {
                console.log('*');
            });
    }
    
    
    getFormResponses('<%= @selected_status %>', '<%= @kommunity.slug %>', '<%= @edfeg.id %>', '<%= @page %>');
  </script>
</section>

app/views/data_form_entities/form_responses_data.js.erb
{
  <% @responses.each.with_index((@count * (@page - 1)) + 1) do |response, index| %>

    $('#form-responses-container').append($('<%= escape_javascript render "data_form_entities/form_response_row", dferg: response, index: index %>'));

  <% end %>

  if('<%= @pending_data %>' == 'true'){
      getFormResponses('<%= @selected_status %>', '<%= @kommunity.slug %>', '<%= @edfeg.id %>', '<%= @page + 1 %>');
  }
}