config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  authenticate :user do
    mount Resque::Server => "/resque"
  end

  # Mount letter_opener web interface
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Test email route
  get 'test_email', to: 'test_emails#send_test'

  namespace :admin do
    resources :users
  end

  resources :kommunities, only: [:new, :create, :edit, :update], param: :kommunity

  scope ':kommunity' do

    get '/',
        to: 'kommunities#show',
        as: :kommunity_show

    resources :events, only: [:index, :new, :create, :edit, :update, :show] do
      member do

        post 'assign-data-form',
             to: 'event_data_form_entity_groups#assign_data_form_entity',
             as: :assign_data_form

        post 'create-form-set',
             to: 'event_data_form_entity_groups#create',
             as: :create_form_set

        delete 'destroy-form-set',
               to: 'event_data_form_entity_groups#destroy',
               as: :destroy_form_set


        get 'update-registration-status-counter',
            to: 'event_data_form_entity_groups#update_registration_status_counter',
            as: :update_registration_status_counter


        delete 'remove-data-form-entity',
               to: 'data_form_entities_events#remove_data_form_entity',
               as: :remove_data_form_entity

        post 'form/update-visibility',
            to: 'data_form_entities_events#update_visibility',
            as: :update_form_visibility


        put 'update-event-status',
            to: 'events#update_event_status',
            as: :update_event_status

        put 'update-header-image',
            to: 'events#update_header_image',
            as: :update_header_image


        get 'all-responses',
            to: 'events#all_responses',
            as: :all_responses


        get 'resources',
            to: 'events#public_resources',
            as: :public_resources


        get 'session-discussions',
            to: 'speaker_resources#session_discussions',
            as: :session_discussion


        resources :event_location_tracks, path: 'event-location-tracks', only: [:create, :destroy], shallow: true do
          resources :track_slots, path: 'track-slots', only: [:create, :destroy], shallow: true
        end


        resources :comments, only: [:create, :destroy], shallow: true do
          resources :comments, only: [:create, :destroy]
        end


        resources :speaker_resources, path: 'speaker-resources', only: [:new, :create, :update]


      end

      resources :locations, only: [:create, :destroy]

      resources :event_updates, only: [:create, :destroy]

    end

    resources :data_forms, path: 'data-forms', only: [:new, :create, :edit, :update]


    resources :event_entry_passes, path: 'event-entry-passes', only: [:create] do
      member do
        patch :toggle_attendance, as: 'toggle-attendance'
        patch :toggle_uninvited, as: 'toggle-uninvited'
      end

      collection do
        get :auto_attendance, as: 'auto-attendance'
        patch :mark_attendance, as: 'mark-attendance'
      end
    end




    # INDIVIDUAL URLS

    # data_form_entity_responses_controller
    get 'fill-form',
        to: 'data_form_entity_responses#fill_form',
        as: :fill_form_response


    post 'response',
         to: 'data_form_entity_responses#submit_form',
         as: :submit_form_response

    put 'form-responses/update-registration_status',
        to: 'data_form_entity_response_groups#update_registration_status',
        as: :update_response_registration_status



    get 'update-rsvp',
        to: 'data_form_entity_response_groups#update_rsvp',
        as: :update_rsvp



    # data_form_entities_controller
    get 'form-responses',
        to: 'data_form_entities#form_responses',
        as: :form_responses

    get 'form-responses-data',
        to: 'data_form_entities#form_responses_data',
        as: :form_responses_data


    # data_form_entity_responses_controller
    put 'user-event-locations/update-selected-location',
        to: 'user_event_locations#update_selected_location',
        as: :update_user_event_selected_location



    #event_communications_mailer
    resources :event_communication_mailers, path: "event-communication-mailers" do
      collection do
        get :data_form_entity_response_group_rsvp_email, path: "user-rsvp-email"
        post :send_data_form_entity_response_group_rsvp_email, path: "send-user-rsvp-email"
        get :event_data_form_entity_group_rsvp_email, path: "event-users-rsvp-email"
        post :send_event_data_form_entity_group_rsvp_email, path: "send-event-users-rsvp-email"
        get :data_form_entity_response_group_entry_pass_email, path: "user-entry-pass-email"
        post :send_data_form_entity_response_group_entry_pass_email, path: "send-user-entry-pass-email"
        get :event_data_form_entity_group_entry_pass_email, path: "event-users-entry-pass-email"
        post :send_event_data_form_entity_group_entry_pass_email, path: "send-event-users-entry-pass-email"

        get :feedback_email, path: "feedback-email"
        post :send_feedback_email, path: "send-feedback-email"

        get :registration_email, path: "registration-email"
        post :send_registration_email, path: "send-registration-email"
      end
    end

    resources :discussions, only: [:create]

  end


  resources :user_messages, only: [:create]



  match '*all', to: proc { [204, {}, ['']] }, via: :options

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  root "home#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  belongs_to :parent, polymorphic: true


  has_many :user_messages, as: :parent
  has_many :discussion_followers


end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :access_allowed?


  # a discussion should be created only when someone is logged in
  # TODO think about allowing people who didn't attend, to be able to create a discussion
  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user = current_user

    @discussion.save

    DiscussionFollower.find_or_create_by(user_id: current_user.id, discussion_id: @discussion.id)

    if (@discussion.parent_type == 'SpeakerResource')
      DiscussionFollower.find_or_create_by(user_id: @discussion.parent.user.id, discussion_id: @discussion.id)
    end

  end


  # TODO complete this part, only the organizer gets to see the hidden discussions
  def hide

  end


  private

  def discussion_params
    params.require(:discussion).permit(:parent_type, :parent_id, :topic, :description)
  end



end

app/views/discussions/_form.html.erb
<%= form_with model: discussion, url: discussions_path, remote: true, html: {id: "new-discussion-form"} do |f| %>
<div class="form-group">
  <%= f.label :topic %>
  <%= f.text_field :topic, class: 'form-control', required: true %>
</div>
<div class="form-group">
  <%= f.label :description, 'Description*' %>
  <%= f.text_area :description, class: 'form-control tinymce editor', rows: 10 %>
</div>
<div>
  <%= f.hidden_field :parent_type, value: parent_type %>
  <%= f.hidden_field :parent_id, value: parent_id %>
</div>
<div class="form-group">
  <%= f.submit 'Submit', class: 'btn btn-outline-info' %>
</div>
<% end %>

app/views/discussions/_user_discussion.html.erb
<div id="discussion-card-<%= discussion.id %>" class="card user-discussion-card">
  <div class="card-header text-left pt-2 px-3 pb-1">
    <h5 class="m-0">
      <%= discussion.topic %>
    </h5>
    <div class="d-flex">
      <div class="existing-profile-image mt-1">
        <img id="user-profile-image" alt="Your Profile Image" src="<%= url_for(discussion.user.avatar) %>">
      </div>
      <p class="ml-2 pt-1 mb-0"><%= discussion.user.name %></p>
    </div>

  </div>
  <div class="discussion-description">
    <%= discussion.description.html_safe %>
  </div>
  <div class="card-body py-1 px-3">
    <div class="discussion-messages">
      <ul class="discussion-messages-list list-group list-group-flush">
        <% discussion.user_messages.order('created_at').each do |dum| %>
            <%= render 'user_messages/discussion_user_message', user_message: dum %>
        <% end %>
      </ul>

      <div class="discussion-new-message">
        <% if allowed_view?(:user_messages, :create) %>
        <%= form_with model: discussion.user_messages.new, url: user_messages_path, html: {class: "d-flex flex-nowrap"} do |f| %>
        <%= f.hidden_field :parent_id, value: discussion.id %>
        <%= f.hidden_field :parent_type, value: 'Discussion' %>
        <div class="form-group p-0 col-10">
          <%= f.text_area :content, class: 'form-control', rows: 1, placeholder: "Comment", onkeydown: 'textAreaRowIncrementor(event, this);' %>
        </div>
        <div class="col-2">
          <%= button_tag type: 'submit', class: "btn btn-info p-0 ml-1" do %>
          <i class='fas fa-arrow-alt-circle-right fa-2x text-white'></i>
          <% end %>
        </div>
        <% end %>

        <% else %>

        <small>
          <%= link_to "Sign In / Sign Up To Comment" %>

        </small>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/discussions/create.js.erb
{

    let newDiscussion = $("<%= escape_javascript render 'discussions/user_discussion', discussion: @discussion %>");


    $('#new-discussion-form').trigger('reset');
    $('#new-discussion-modal').modal('hide');

    $('#discussions-list-<%= @discussion.parent_id %>').prepend(newDiscussion);
}