config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  authenticate :user do
    mount Resque::Server => "/resque"
  end

  # Mount letter_opener web interface
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Test email route
  get 'test_email', to: 'test_emails#send_test'

  namespace :admin do
    resources :users
  end

  resources :kommunities, only: [:new, :create, :edit, :update], param: :kommunity

  scope ':kommunity' do

    get '/',
        to: 'kommunities#show',
        as: :kommunity_show

    resources :events, only: [:index, :new, :create, :edit, :update, :show] do
      member do

        post 'assign-data-form',
             to: 'event_data_form_entity_groups#assign_data_form_entity',
             as: :assign_data_form

        post 'create-form-set',
             to: 'event_data_form_entity_groups#create',
             as: :create_form_set

        delete 'destroy-form-set',
               to: 'event_data_form_entity_groups#destroy',
               as: :destroy_form_set


        get 'update-registration-status-counter',
            to: 'event_data_form_entity_groups#update_registration_status_counter',
            as: :update_registration_status_counter


        delete 'remove-data-form-entity',
               to: 'data_form_entities_events#remove_data_form_entity',
               as: :remove_data_form_entity

        post 'form/update-visibility',
            to: 'data_form_entities_events#update_visibility',
            as: :update_form_visibility


        put 'update-event-status',
            to: 'events#update_event_status',
            as: :update_event_status

        put 'update-header-image',
            to: 'events#update_header_image',
            as: :update_header_image


        get 'all-responses',
            to: 'events#all_responses',
            as: :all_responses


        get 'resources',
            to: 'events#public_resources',
            as: :public_resources


        get 'session-discussions',
            to: 'speaker_resources#session_discussions',
            as: :session_discussion


        resources :event_location_tracks, path: 'event-location-tracks', only: [:create, :destroy], shallow: true do
          resources :track_slots, path: 'track-slots', only: [:create, :destroy], shallow: true
        end


        resources :comments, only: [:create, :destroy], shallow: true do
          resources :comments, only: [:create, :destroy]
        end


        resources :speaker_resources, path: 'speaker-resources', only: [:new, :create, :update]


      end

      resources :locations, only: [:create, :destroy]

      resources :event_updates, only: [:create, :destroy]

    end

    resources :data_forms, path: 'data-forms', only: [:new, :create, :edit, :update]


    resources :event_entry_passes, path: 'event-entry-passes', only: [:create] do
      member do
        patch :toggle_attendance, as: 'toggle-attendance'
        patch :toggle_uninvited, as: 'toggle-uninvited'
      end

      collection do
        get :auto_attendance, as: 'auto-attendance'
        patch :mark_attendance, as: 'mark-attendance'
      end
    end




    # INDIVIDUAL URLS

    # data_form_entity_responses_controller
    get 'fill-form',
        to: 'data_form_entity_responses#fill_form',
        as: :fill_form_response


    post 'response',
         to: 'data_form_entity_responses#submit_form',
         as: :submit_form_response

    put 'form-responses/update-registration_status',
        to: 'data_form_entity_response_groups#update_registration_status',
        as: :update_response_registration_status



    get 'update-rsvp',
        to: 'data_form_entity_response_groups#update_rsvp',
        as: :update_rsvp



    # data_form_entities_controller
    get 'form-responses',
        to: 'data_form_entities#form_responses',
        as: :form_responses

    get 'form-responses-data',
        to: 'data_form_entities#form_responses_data',
        as: :form_responses_data


    # data_form_entity_responses_controller
    put 'user-event-locations/update-selected-location',
        to: 'user_event_locations#update_selected_location',
        as: :update_user_event_selected_location



    #event_communications_mailer
    resources :event_communication_mailers, path: "event-communication-mailers" do
      collection do
        get :data_form_entity_response_group_rsvp_email, path: "user-rsvp-email"
        post :send_data_form_entity_response_group_rsvp_email, path: "send-user-rsvp-email"
        get :event_data_form_entity_group_rsvp_email, path: "event-users-rsvp-email"
        post :send_event_data_form_entity_group_rsvp_email, path: "send-event-users-rsvp-email"
        get :data_form_entity_response_group_entry_pass_email, path: "user-entry-pass-email"
        post :send_data_form_entity_response_group_entry_pass_email, path: "send-user-entry-pass-email"
        get :event_data_form_entity_group_entry_pass_email, path: "event-users-entry-pass-email"
        post :send_event_data_form_entity_group_entry_pass_email, path: "send-event-users-entry-pass-email"

        get :feedback_email, path: "feedback-email"
        post :send_feedback_email, path: "send-feedback-email"

        get :registration_email, path: "registration-email"
        post :send_registration_email, path: "send-registration-email"
      end
    end

    resources :discussions, only: [:create]

  end


  resources :user_messages, only: [:create]



  match '*all', to: proc { [204, {}, ['']] }, via: :options

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  root "home#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kommunity.rb
class Kommunity < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
  has_many :data_forms
  has_many :user_roles_users


  has_one_attached :logo_image


  # get the nearest event which took place or has to take place
  def nearest_time_events

    events = Event.upcoming(kommunity_id: self.id)
    if events.blank?
      events = Event.recent_past(kommunity_id: self.id)
    end

    return events
  end


  def member_count
    return self.user_roles_users.distinct(:user_id).length
  end





end

app/controllers/kommunities_controller.rb
class KommunitiesController < ApplicationController
  before_action :authenticate_user!, except: [:show]


  def show
    @events = Event.where(kommunity_id: @kommunity.id)

    @upcoming_events = Event.includes(event_data_form_entity_groups: :data_form_entities).upcoming(kommunity_id: @kommunity.id)
    @recent_past_events = Event.includes(event_data_form_entity_groups: :data_form_entities).recent_past(kommunity_id: @kommunity.id)

  end

  def new
    @kommunity = Kommunity.new
  end


  def create
    kommunity = Kommunity.new(kommunity_params)
    kommunity.user = current_user
    kommunity.save

    # we will make an autocomplete for assigning organizers to the community
    # UserRolesUser.create(user: current_user, kommunity: kommunity, user_role: UserRole.find_by_name(NameValues::UserRoleType::ORGANIZER))

    redirect_to kommunity_show_path(kommunity.slug)

  end


  def edit

  end


  def update

    @kommunity.update(kommunity_params)
    redirect_to kommunity_show_path(@kommunity.slug)
  end


  private

  def kommunity_params

    params.require(:kommunity_form).permit(:name, :about, :logo_image, :mini_description)
  end



end

app/views/kommunities/_display_card.html.erb
<div class="kommunity-display-card">
  <div class="card">
    <div class="card-header bg-white border-0 d-flex flex-column justify-content-center align-items-center">
      <%= link_to '', kommunity_show_path(kommunity), class: "clickable-card full-size" %>
      <% if kommunity.logo_image.attached? %>
        <div class="kommunity-logo-image">
          <img  alt="<%= kommunity.name %> Logo" src="<%= url_for(kommunity.logo_image)%>">
        </div>
      <% end %>
      <p class="mb-0 mt-1 ">
        <%= kommunity.name %>
      </p>
    </div>
    <div class="card-body text-center">
      <%= link_to '', kommunity_show_path(kommunity), class: "clickable-card full-size" %>
      <p><%= kommunity.mini_description %></p>
    </div>
    <div class="card-footer d-flex flex-wrap justify-content-around">
      <% if !kommunity.nearest_time_events.blank? %>
        <%= link_to '', event_path(kommunity, kommunity.nearest_time_events[0]), class: "clickable-card full-size" %>
        <% if kommunity.nearest_time_events[0].start_time > Time.now %>
          <p class="mb-0"><small>Upcoming:</small> </p>
        <% else %>
          <p class="mb-0"><small>Última edición: </small> </p>
        <% end %>
        <p class="font-weight-bold mb-0">
          <%= kommunity.nearest_time_events[0].name %>
          <span class="badge badge-pill badge-info"><%= kommunity.nearest_time_events[0].start_time.strftime('%d-%B-%Y') %></span>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/kommunities/_form.html.erb
<%= form_with model: @kommunity, scope: :kommunity_form, local: true do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, class: 'form-control' %>
</div>

<div class="form-group profile-image-input text-center position-relative">
  <div class="existing-logo-image">
    <img id="logo-image-show" alt="Logo Image" src="<%= @kommunity.logo_image.attached? ? url_for(@kommunity.logo_image) : '' %>">
  </div>

  <%= f.label :logo_image, 'Logo Image', for: 'logo-image', class: 'custom-file-label' %>
  <%= f.file_field :logo_image, class: 'custom-file-input', id: 'logo-image', onchange: 'showImage(this, "logo-image-show");', accept: "image/*" %>

</div>

<div class="form-group">
  <%= f.label :mini_description %>
  <%= f.text_field :mini_description, required: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :about %>
  <%= f.text_area :about, :class => "tinymce editor", :rows => 3, :cols => 50 %>
</div>

<div class="form-group">

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
</div>


<% end  %>

app/views/kommunities/edit.html.erb
<section id="create-kommunity">


  <div class="card col-md-8 offset-md-2">
    <h3 class="card-header">Update Info: <span class="text-info"><%= @kommunity.name %></span> </h3>
      <div class="card-body">
        <%= render 'form' %>
      </div>

  </div>

</section>

app/views/kommunities/new.html.erb
<section id="create-kommunity">
  <div class="card col-md-8 offset-md-2">
    <h3 class="card-header">Crear un curso</h1>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/kommunities/show.html.erb
<% content_for :page_title do %>
  <%= @kommunity.name %>
<% end %>
<section id="kommunity-<%= @kommunity.id %>">
  <div class="card bg-white p-3 mb-3 d-flex flex-row flex-wrap">
    <div class="col-md-3 d-flex flex-column align-items-center">
      <% if @kommunity.logo_image.attached? %>
        <div class="kommunity-logo-image-large">
          <img  alt="<%= @kommunity.name %> Logo" src="<%= url_for(@kommunity.logo_image)%>">
        </div>
      <% end %>
      <h4 class="text-secondary mt-3">
        <%= @kommunity.name %>
      </h4>
      <% if allowed_view?(:kommunities, :edit) %>
        <span class="badge badge-primary badge-pill mt-2">
          <%= link_to 'Editar', edit_kommunity_path(@kommunity), class: 'text-white' %>
        </span>
      <% end %>
    </div>
    <div class="col-md-9" id="about-community">
      <div class="pl-5 pt-3">
        <%= @kommunity.about.html_safe %>
      </div>
    </div>
  </div>
  <% if allowed_view?(:events, :create) && current_user.organizer?(@kommunity.id) %>
    <div class="card my-4 p-3 d-flex flex-row justify-content-start">
      <%=  link_to new_event_path, class: 'mr-4 btn btn-outline-secondary', target: "_blank" do %>
        <span><i class="fas fa-plus-circle fa-1x text-success"></i> Crear seminario</span>
      <% end %>
      <%=  link_to new_data_form_path, class: 'mr-4 btn btn-outline-secondary', target: "_blank" do %>
        <span><i class="fas fa-plus-circle fa-1x text-success"></i> Crear formulario </span>
      <% end %>
    </div>
  <% end %>
  <% if user_signed_in? && current_user.organizer?(@kommunity.id) %>
    <div class="row">
      <div class="accordion col-md-4" id="kommunity-events">
        <!--upcoming events-->
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Próximos seminarios
              </button>
            </h5>
          </div>
          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#kommunity-events">
            <div class="card-body">
              <ul class="list-group">
                <% @events.select{|ev| ev.start_time >= Time.now.beginning_of_day && ev.status?([NameValues::EventStatusType::ANNOUNCED, NameValues::EventStatusType::OPEN])}.each do |event| %>
                  <li class="list-group-item">
                    <%= link_to event.name.titleize, event_path(id: event), target: "_blank" %>
                    <%= render 'events/event_time_display', event: event %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!-- drafts -->
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Seminarios en borrador
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#kommunity-events">
            <div class="card-body">
              <ul class="list-group">
                <% @events.select{|ev| ev.status?([NameValues::EventStatusType::DRAFT])}.each do |event| %>
                  <li class="list-group-item">
                    <%= link_to event.name.titleize, event_path(id: event), target: "_blank", class: 'text-secondary' %>
                    <%= render 'events/event_time_display', event: event %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!-- past + cancelled events -->
        <div class="card">
          <div class="card-header" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Seminarios pasados
              </button>
            </h5>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#kommunity-events">
            <div class="card-body">
              <ul class="list-group">
                <% @events.select{|ev| ev.start_time <= Time.now.beginning_of_day && !ev.status?([NameValues::EventStatusType::DRAFT])}.each do |event| %>
                  <li class="list-group-item bg-light">
                    <%= link_to event.name.titleize, event_path(id: event), target: "_blank", class: 'text-muted' %>
                    <%= render 'events/event_time_display', event: event %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 card p-0">
        <ul class="list-group list-group-flush">
          <li class="list-group-item list-group-item-primary">
            <h5 class="m-0">Formularios</h5>
          </li>
          <% @kommunity.data_forms.order('created_at desc').each do |df| %>
            <li class="list-group-item">
              <%= link_to df.name, edit_data_form_path(@kommunity, df) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <% if !@upcoming_events.empty? %>
    <div class="col-md-10 offset-md-1 horizontal-cards mb-5">
      <div>
        <h3 class="border-bottom text-secondary">Upcoming Events</h3>
      </div>
      <div class="row d-flex flex-md-row flex-sm-column flex-nowrap">
        <% @upcoming_events.each do |event| %>
          <div class="col-md-4 m-2 p-0">
            <%= render 'events/event_mini_card', event: event %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if !@recent_past_events.empty? %>
    <div class="col-md-10 offset-md-1 horizontal-cards">
      <div>
        <h3 class="border-bottom text-secondary">Recent Past Events</h3>
      </div>
      <div class="row d-flex flex-md-row flex-sm-column flex-nowrap">
        <% @recent_past_events.each do |event| %>
          <div class="m-2 p-0">
            <%= render 'events/event_mini_card', event: event %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</section>