config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  authenticate :user do
    mount Resque::Server => "/resque"
  end

  # Mount letter_opener web interface
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Test email route
  get 'test_email', to: 'test_emails#send_test'

  namespace :admin do
    resources :users
  end

  resources :kommunities, only: [:new, :create, :edit, :update], param: :kommunity

  scope ':kommunity' do

    get '/',
        to: 'kommunities#show',
        as: :kommunity_show

    resources :events, only: [:index, :new, :create, :edit, :update, :show] do
      member do

        post 'assign-data-form',
             to: 'event_data_form_entity_groups#assign_data_form_entity',
             as: :assign_data_form

        post 'create-form-set',
             to: 'event_data_form_entity_groups#create',
             as: :create_form_set

        delete 'destroy-form-set',
               to: 'event_data_form_entity_groups#destroy',
               as: :destroy_form_set


        get 'update-registration-status-counter',
            to: 'event_data_form_entity_groups#update_registration_status_counter',
            as: :update_registration_status_counter


        delete 'remove-data-form-entity',
               to: 'data_form_entities_events#remove_data_form_entity',
               as: :remove_data_form_entity

        post 'form/update-visibility',
            to: 'data_form_entities_events#update_visibility',
            as: :update_form_visibility


        put 'update-event-status',
            to: 'events#update_event_status',
            as: :update_event_status

        put 'update-header-image',
            to: 'events#update_header_image',
            as: :update_header_image


        get 'all-responses',
            to: 'events#all_responses',
            as: :all_responses


        get 'resources',
            to: 'events#public_resources',
            as: :public_resources


        get 'session-discussions',
            to: 'speaker_resources#session_discussions',
            as: :session_discussion


        resources :event_location_tracks, path: 'event-location-tracks', only: [:create, :destroy], shallow: true do
          resources :track_slots, path: 'track-slots', only: [:create, :destroy], shallow: true
        end


        resources :comments, only: [:create, :destroy], shallow: true do
          resources :comments, only: [:create, :destroy]
        end


        resources :speaker_resources, path: 'speaker-resources', only: [:new, :create, :update]


      end

      resources :locations, only: [:create, :destroy]

      resources :event_updates, only: [:create, :destroy]

    end

    resources :data_forms, path: 'data-forms', only: [:new, :create, :edit, :update]


    resources :event_entry_passes, path: 'event-entry-passes', only: [:create] do
      member do
        patch :toggle_attendance, as: 'toggle-attendance'
        patch :toggle_uninvited, as: 'toggle-uninvited'
      end

      collection do
        get :auto_attendance, as: 'auto-attendance'
        patch :mark_attendance, as: 'mark-attendance'
      end
    end




    # INDIVIDUAL URLS

    # data_form_entity_responses_controller
    get 'fill-form',
        to: 'data_form_entity_responses#fill_form',
        as: :fill_form_response


    post 'response',
         to: 'data_form_entity_responses#submit_form',
         as: :submit_form_response

    put 'form-responses/update-registration_status',
        to: 'data_form_entity_response_groups#update_registration_status',
        as: :update_response_registration_status



    get 'update-rsvp',
        to: 'data_form_entity_response_groups#update_rsvp',
        as: :update_rsvp



    # data_form_entities_controller
    get 'form-responses',
        to: 'data_form_entities#form_responses',
        as: :form_responses

    get 'form-responses-data',
        to: 'data_form_entities#form_responses_data',
        as: :form_responses_data


    # data_form_entity_responses_controller
    put 'user-event-locations/update-selected-location',
        to: 'user_event_locations#update_selected_location',
        as: :update_user_event_selected_location



    #event_communications_mailer
    resources :event_communication_mailers, path: "event-communication-mailers" do
      collection do
        get :data_form_entity_response_group_rsvp_email, path: "user-rsvp-email"
        post :send_data_form_entity_response_group_rsvp_email, path: "send-user-rsvp-email"
        get :event_data_form_entity_group_rsvp_email, path: "event-users-rsvp-email"
        post :send_event_data_form_entity_group_rsvp_email, path: "send-event-users-rsvp-email"
        get :data_form_entity_response_group_entry_pass_email, path: "user-entry-pass-email"
        post :send_data_form_entity_response_group_entry_pass_email, path: "send-user-entry-pass-email"
        get :event_data_form_entity_group_entry_pass_email, path: "event-users-entry-pass-email"
        post :send_event_data_form_entity_group_entry_pass_email, path: "send-event-users-entry-pass-email"

        get :feedback_email, path: "feedback-email"
        post :send_feedback_email, path: "send-feedback-email"

        get :registration_email, path: "registration-email"
        post :send_registration_email, path: "send-registration-email"
      end
    end

    resources :discussions, only: [:create]

  end


  resources :user_messages, only: [:create]



  match '*all', to: proc { [204, {}, ['']] }, via: :options

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  root "home#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event_data_form_entity_group.rb
class EventDataFormEntityGroup < ApplicationRecord
  acts_as_paranoid
  # extend FriendlyId
  # friendly_id :name, use: :slugged

  belongs_to :event
  belongs_to :registration_type
  belongs_to :user

  has_many :data_form_entities, as: :entity, dependent: :destroy
  has_many :data_form_entity_response_groups
  has_many :fixed_email_edfegs


  validates_length_of :data_form_entities, maximum: 1

  # scopes
  default_scope { includes(:registration_type, :event) }

  ##



  def registration_type? (registration_type_names)
    return registration_type_names.include? self.registration_type.name
  end



  def registration_status_counts
    statuses = Hash.new
    dfergs = self.data_form_entity_response_groups
    self.registration_type.registration_type_statuses.includes(:registration_status).each do |regst|
      statuses[regst.registration_status.name.to_s] = {
          count: dfergs.select{|dferg| dferg.registration_status_id == regst.registration_status.id}.length,
          registration_status_id: regst.registration_status_id
      }

    end

    return statuses
  end


end

app/controllers/event_data_form_entity_groups_controller.rb
class EventDataFormEntityGroupsController < ApplicationController
  # before_action :set_kommunity
  before_action :authenticate_user!
  before_action :set_event
  before_action :set_event_data_form_entity_group, only: [:assign_data_form_entity, :destroy, :update_registration_status_counter]
  before_action :access_allowed?



  def create

    if(@event.event_data_form_entity_groups.where(name: event_data_form_entity_groups_controller_params[:name]).blank?)
      @edfeg = EventDataFormEntityGroup.new(event_data_form_entity_groups_controller_params)
      @edfeg.event = @event
      @edfeg.user = current_user
      @edfeg.save
    else
      return error_response(ErrorNotification::ResponseTypes::JS, ErrorNotification::ErrorCodes::CONFLICT, "Form Set Names Should Be Unique")
    end
  end


  def destroy
  #   check if any responses are present in the EventDataFormEntityGroup
    existing_responses = DataFormEntityResponse.joins(:data_form_entity).where(
        "data_form_entities.entity_id = ? and data_form_entities.entity_type = ?",
        @edfeg, EventDataFormEntityGroup
    )

    if(!existing_responses.blank?)
      return error_response(ErrorNotification::ResponseTypes::JS, ErrorNotification::ErrorCodes::UNAUTHORIZED, "Cannot be deleted as it has responses")
    end

    @edfeg_id = @edfeg.id
    @edfeg.destroy
  end


  def assign_data_form_entity
    data_form = DataForm.find_by(id: params[:data_form_id], kommunity_id: @event.kommunity_id)

    if data_form
      # if event already has a data form, then don't add, else add that data form, this just a safety measure to prevent duplicacy
      if @edfeg.data_form_entities.where(data_form: data_form).blank?
        @dfe = DataFormEntity.new(entity: @edfeg, data_form: data_form, name: data_form.name)
        @dfe.save
      else
        return error_response(ErrorNotification::ResponseTypes::JS, ErrorNotification::ErrorCodes::CONFLICT, "This form is already added to the event")
      end



    end


  end


  # method to update the counter for a specific event data form entity group
  # this will return a script to the browser which will updated the counter every time this route is called
  def update_registration_status_counter
    @selected_status = params[:selected_status_id]
  end



  private

  def set_event
    @event = Event.includes(:user, event_data_form_entity_groups: {data_form_entities: :data_form}).find_by(slug: params[:id], kommunity_id: @kommunity.id)
    RolePermission.event = @event
  end

  def set_event_data_form_entity_group
    @edfeg = EventDataFormEntityGroup.find(params[:event_data_form_entity_group_id])
  end

  def event_data_form_entity_groups_controller_params

    params.require(:event_data_form_entity_group).permit(:name, :registration_type_id)
  end


end

app/views/event_data_form_entity_groups/_assigned_form_list_item.html.erb
<li class="data-form-entity-<%= dfe.id %>">
  <div class="mt-2 d-flex">
    <p class="d-flex justify-content-start">
      <%= dfe.data_form.name %>
    </p>

    <div class="card p-3 ml-3 mr-3">
      <%= render 'event_data_form_entity_groups/assigned_form_list_item_actions', dfe: dfe %>
    </div>

    <% if dfe.data_form_entity_responses.length == 0 %>
    <%= link_to remove_data_form_entity_event_path(id: @event, entity_id: dfe), remote: true, method: :delete, class: "close ml-2 text-danger", 'aria-label': 'Remove' do %>

    <span aria-hidden="true">&times;</span>
    <% end %>
    <% end %>


  </div>


</li>

app/views/event_data_form_entity_groups/_assigned_form_list_item_actions.html.erb
<div class="d-flex">
  <div class="d-flex">
    <span class="mr-2">Visible para:</span>
    <%= form_with url: update_form_visibility_event_path(data_form_entity: dfe), method: :post, remote: true do |f| %>
      <%= f.select :visibility, options_for_select(DataFormEntity.visibilities.keys.map { |key| [translate_to_es(key), key] }, dfe.visibility), {}, { onchange: 'Rails.fire(this.form, "submit")', class: 'form-control' } %>
    <% end %>
  </div>
  <!--<% link_to 'Fill', fill_form_response_path(data_form_entity_id: dfe), class: 'ml-2 text-primary' %>-->
  <% if dfe.entity.registration_type?(NameValues::RegistrationsType::FEEDBACK) %>
    <div class="ml-2">
      <%= link_to "Send Remaining Feedback Emails", feedback_email_event_communication_mailers_path(event: dfe.entity.event, form: dfe, force: false), remote: true %>
      <br>
      <%= link_to "Resend Feedback Emails", feedback_email_event_communication_mailers_path(event: dfe.entity.event, form: dfe, force: true), remote: true %>
    </div>
  <% elsif dfe.entity.registration_type?([NameValues::RegistrationsType::ATTENDEE, NameValues::RegistrationsType::SPEAKER]) %>
    <div class="ml-2">
      <%= link_to t('mailers.send_emails_to', type: translate_to_es(dfe.entity.registration_type.name)), registration_email_event_communication_mailers_path(dfe: dfe), remote: true %>
    </div>
  <% end %>
  <%= link_to 'Rellenar para un miembro', fill_form_response_path(data_form_entity_id: dfe, for_other_user: true), class: 'ml-2 text-primary' %>
</div>

app/views/event_data_form_entity_groups/_form_set.html.erb
<li class="list-group-item list-group-item-action flex-column align-items-start" id="event-data-form-entity-group-<%= edfeg.id %>">
  <div class="d-flex justify-content-start">
    <h5 class="mb-1 mr-3">
      <%= edfeg.name %>
      <small>(<%= translate_to_es(edfeg.registration_type.name) %>)</small>
    </h5>
    <div>
      <%= link_to 'Ver respuestas', form_responses_path(event_data_form_entity_group_id: edfeg), class: 'btn btn-outline-info' %>
      <% if DataFormEntityResponse.joins(:data_form_entity).where("data_form_entities.entity_id = ? and data_form_entities.entity_type = ?",  @edfeg, EventDataFormEntityGroup) %>
        <%= link_to 'Borrar', destroy_form_set_event_path(id: event, event_data_form_entity_group_id: edfeg), method: :delete, remote: true, class: 'btn btn-outline-warning' %>
      <% end %>
    </div>
  </div>
  <ul id="event-data-form-entities-<%= edfeg.id %>">
    <%= render partial: 'event_data_form_entity_groups/assigned_form_list_item', collection: edfeg.data_form_entities, as: :dfe, locals: {edfeg: edfeg} %>
  </ul>
  <div class="add-form-container <% if edfeg.data_form_entities.length > 0 %>d-none<% end %>">
    <!--Assign the forms using JS requests, create a page to fill the assigned form and create a user's entry-->
    <!--add feature to enable/disable the new data_form_entity-->
    <%= form_with url: assign_data_form_event_path(id: event, event_data_form_entity_group_id: edfeg), method: 'post', remote: true do |f| %>
      <h6>Select Form</h6>
      <div class="form-group">
        <%= f.label :data_form %>
        <%= f.select :data_form_id, options_for_select(edfeg.event.kommunity.data_forms.all.collect{|m| [m.name, m.id]}), {required: true}, class: 'form-control' %>
        <%= f.submit "Assign Form", class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</li>

app/views/event_data_form_entity_groups/_registration_status_counter_filter.html.erb
<div class="registration-status-counter" id="registration-status-counter-filter-<%= edfeg.id %>">

  <ul class="list-group d-flex flex-row">
      <li class="list-group-item p-1 <%= selected_status.blank? ? 'active' : '' %>" data-regstatus="all">
        <%= link_to "All : #{edfeg.data_form_entity_response_groups.length}", form_responses_path(event_data_form_entity_group_id: edfeg) %>
      </li>
    <% edfeg.registration_status_counts.each do |k, v| %>
      <li class="list-group-item p-1 <%= selected_status.to_i == v[:registration_status_id].to_i ? 'active' : '' %>" data-regstatus="<%= v[:registration_status_id].to_i  %>">

        <%= link_to "#{k.titleize} : #{v[:count]}", form_responses_path(event_data_form_entity_group_id: edfeg, registration_status: v[:registration_status_id]) %>
      </li>

    <% end %>

  </ul>


</div>

app/views/event_data_form_entity_groups/assign_data_form_entity.js.erb
{

 function addAssignedForm(){
     let newAssignedFormListItem = $('#event-data-form-entities-<%= @edfeg.id %>');

     newAssignedFormListItem.append("<%= escape_javascript render 'assigned_form_list_item', dfe: @dfe, event: @event %>");

     newAssignedFormListItem.siblings('.add-form-container').addClass('d-none');


     let notification = new Noty({
         text: 'New Form Assigned',
         theme: 'relax',
         type: 'success',
         timeout: 1500
     }).show();
 }


 addAssignedForm();

}

app/views/event_data_form_entity_groups/create.js.erb
{

    function addFormSet(){
        let newAssignedFormListItem = $('#form-set-list').append($("<%= escape_javascript render 'event_data_form_entity_groups/form_set', edfeg: @edfeg, event: @event %>"));


        let notification = new Noty({
            text: 'New Form Set Created',
            theme: 'relax',
            type: 'success',
            timeout: 1500
        }).show();
    }


    addFormSet();

}

app/views/event_data_form_entity_groups/destroy.js.erb
{

    function removeFormSet(){
        $('#event-data-form-entity-group-<%= @edfeg.id %>').remove();


        let notification = new Noty({
            text: 'Form set deleted',
            theme: 'relax',
            type: 'warning',
            timeout: 1500
        }).show();
    }


    removeFormSet();

}

app/views/event_data_form_entity_groups/update_registration_status_counter.js.erb
{

    $("#registration-status-counter-filter-<%= @edfeg.id %>").replaceWith($("<%= escape_javascript render 'event_data_form_entity_groups/registration_status_counter_filter', edfeg: @edfeg, selected_status: @selected_status %>"));

}